[versions]
# Versions
androidMinSdkVersion = "21"
androidTargetSdkVersion = "33"
androidCompileSdkVersion = "33"

androidVersion = "11.1.0"
autoMinSdkVersion = "23"
autoTargetSdkVersion = "33"
autoCompileSdkVersion = "33"

composeMinSdkVersion = "23"
composeTargetSdkVersion = "33"
composeCompileSdkVersion = "33"

exampleMinSdkVersion = "23"
exampleTargetSdkVersion = "33"
exampleCompileSdkVersion = "33"
exampleNdkVersion = "21.4.7075529"

# Plugins
hiltAndroidVersion = "2.46"
hiltAndroidCompilerVersion = "2.46"
kotlinxMetadataJvmVersion = "0.6.0"
lifecycleAndroidVersion = "0.1.12"
loggingInterceptorVersion = "4.12.0"
mapboxSdkTurfVersion = "6.15.0"
mapsComposeVersion = "0.1.0"
mapsStyleVersion = "11.1.0"
messageAdapterGsonVersion = "0.1.12"
okhttpVersion = "4.12.0"

# Dependencies
androidxActivityCompose = "1.8.2"
androidxAppcompat = "1.6.1"
androidxCore = "1.12.0"
androidxLifecycle = "2.7.0"

materialDesign = "1.11.0"
composeBom = "2024.01.00"

androidxHiltNavigationCompose = "1.1.0"
roomKtxVersion = "2.6.1"
scarletVersion = "0.1.12"
websocketOkhttpVersion = "0.1.12"
streamAdapterCoroutinesVersion = "0.1.12"
material3Version = "1.2.0-rc01"


[libraries]

# Dependencies
android = { module = "com.mapbox.maps:android", version.ref = "androidVersion" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }


androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtxVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtxVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomKtxVersion" }
androidx-room-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtxVersion" }

androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidxLifecycle" }
androidx-lifecycleKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
googleMaterialDesign = { module = "com.google.android.material:material", version.ref = "materialDesign" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidVersion" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompilerVersion" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }

kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinxMetadataJvmVersion" }
lifecycle-android = { module = "com.tinder.scarlet:lifecycle-android", version.ref = "lifecycleAndroidVersion" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptorVersion" }
mapbox-sdk-turf = { module = "com.mapbox.mapboxsdk:mapbox-sdk-turf", version.ref = "mapboxSdkTurfVersion" }
maps-compose = { module = "com.mapbox.extension:maps-compose", version.ref = "mapsComposeVersion" }
maps-style = { module = "com.mapbox.extension:maps-style", version.ref = "mapsStyleVersion" }
message-adapter-gson = { module = "com.tinder.scarlet:message-adapter-gson", version.ref = "messageAdapterGsonVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
scarlet = { module = "com.tinder.scarlet:scarlet", version.ref = "scarletVersion" }
websocket-okhttp = { module = "com.tinder.scarlet:websocket-okhttp", version.ref = "websocketOkhttpVersion" }
stream-adapter-coroutines = { module = "com.tinder.scarlet:stream-adapter-coroutines", version.ref = "streamAdapterCoroutinesVersion" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Version" }


[bundles]

[plugins]